DreamWay-Media/dwm-wp-theme

- README.md
Removed assets to be able to make repo public.
https://app.asana.com/0/1208404305074169/1208459363006104/f
> Remove assets

- style.css
- template-parts/template-home.php
Added new style and fade up animation
> Re: start now button styling

- template-parts/template-home.php
- template-parts/template-projects.php
DWM - Portfolio page - images should be linked to the detail page as the titles
[Link](https://app.asana.com/0/599212887649773/1208514002790435/f)
> images linked to the details page

- style.css
- template-parts/template-projects.php
https://app.asana.com/0/599212887649773/1208523547188755/f
Aligned title and text to top of container, for portfolio page.
> Dwmportfoliotextandtitle

- style.css
- template-parts/template-contact.php
DWM - contact us page - remove social media icons
[Link](https://app.asana.com/0/599212887649773/1208523547188785/f)
> remove social media icons from contact us page

- style.css
https://app.asana.com/0/599212887649773/1208523547188761/f
Added spacing to bottom of blog cards.
> Addspacingtoblogcards

- style.css
DWM - Footer Menu wraps into to lines
[link](https://app.asana.com/0/599212887649773/1208534958592597/f)
> footer menu in horizontal line

- single.php
- style.css
DWM - Blog Page - Fix social buttons in comment section
[Link](https://app.asana.com/0/599212887649773/1208553355808116/f)
> Social buttons are responsive

- style.css
DWM - Footer Menu wraps into to lines
[Link](https://app.asana.com/0/599212887649773/1208534958592597/f)
> footer menu appears in straight line

- functions.php
- style.css
- template-parts/template-contact.php
Added testimonials to the bottom of the contact page using the existing carousel on the homepage.
https://app.asana.com/0/1208404305074169/1208523547188787/f
> Add testimonials to the bottom of the contact page

- style.css
- template-parts/template-home.php
Created ACF for displaying: Feat Blog title, Feat Blog desc, Feat Blog More Button Text.
Created Featured Blog section designed to display 3 maximum blog posts, and a button to link to blog page.
https://app.asana.com/0/599212887649773/1208523547188783/f
> Created a Featured Blog section in HP. Created ACF for Featured Blogs.

- style.css
- template-parts/template-contact.php
Removed featured reviews section and removed the unused styles for it.
https://app.asana.com/0/1208404305074169/1208523547188787/f
> Remove featured reviews section from contact page

- footer.php
- functions.php
- style.css
- template-parts/template-contact.php
- template-parts/template-home.php
Integrated hero slider to website. Created hero slide field group to be able to manage the slides in the back end. In order to use, you must open the Hero Slide Field Group and set Post Type equal to Hero Slides. Then you can create slides by adding in images, text, links, and SEO tags (including titles and descriptions).
https://app.asana.com/0/1208404305074169/1208459363006096/f
> Integrate hero slider to website

- functions.php
DWM - Add accessibility feature to the website 
[Link](https://app.asana.com/0/599212887649773/1208562315891816)
> embedded script

- style.css
DWM - Footer Menu wraps into to lines
[Link](https://app.asana.com/0/599212887649773/1208534958592597/f)
> applied styling to 1202px and 1384px

- style.css
- template-parts/template-home.php
- template-parts/template-projects.php
DWM - Portfolio - Match the start now button styling with the one in the homepage
[Link](https://app.asana.com/0/599212887649773/1208562315891797/f)
> enabled styling in start now button.

- style.css
- template-parts/template-home.php
DWM - Edit buttons to match each other
[Link](https://app.asana.com/0/599212887649773/1208543400570257/f)
> changed background of button to green

- footer.php
- style.css
Removed the owl dots from the slider and disabled sliding functionality. Removed owl dot styles as well.
https://app.asana.com/0/599212887649773/1208459363006096/f
> Remove owl dots and sliding functionality

- style.css
- template-parts/template-home.php
URGENT - DWM - HP - Services Typos
[Link](https://app.asana.com/0/599212887649773/1208572817886273/f)
> added links and changed spelling

- template-parts/template-home.php
Ticket Link:https://app.asana.com/0/599212887649773/1208572817886276/f
Created Our Services Button in HP
> Hp service button

- footer.php
- style.css
When there is only one slide, no dots will be displayed and dragging/sliding is disabled. When there is more than two slides, dots will be displayed and dragging/sliding is enabled.
https://app.asana.com/0/599212887649773/1208459363006096/f
> Only display dots when there is more than one slide

- template-parts/template-projects.php
Task link: https://app.asana.com/0/1208404278452601/1208571837055121/f
All the project images on the portfolio page have respective project detail page links attached to it.
> feat: made listing images clickable with post URLs in PP

- style.css
DWM - HP - Featured Projects - Mobile - Add spacing between thumbnail and the title
[Link](https://app.asana.com/0/599212887649773/1208594946846708/f)
> added spacing for mobile 

- style.css
DWM - Portfolio - Match the start now button styling with the one in the homepage
[Link](https://app.asana.com/0/599212887649773/1208562315891797/f)
> changed background

- style.css
DWM - Edit buttons to match each other
[Link](https://app.asana.com/0/599212887649773/1208543400570257/f)
> added border while hover

- functions.php
- template-parts/template-home.php
Successfully made each service dynamically pulled from the database.
https://app.asana.com/0/1208404305074169/1208562315891802/f
> Make each service dynamically pulled from database

- functions.php
Made sure that there was proper order for the services
https://app.asana.com/0/599212887649773/1208605886979064/f
> Ensure proper ordering for each service

- footer.php
- style.css
- template-parts/template-demo.php
- template-parts/template-home.php
Creating the demo for ltw, need to reformat to allow slugs for different projects.
> created demo for ltw, need to update asap.

- style.css
- template-parts/template-home.php
Fixed styling for other headers including vertically centering and evenly spacing home page header. Also removed an extra scroll down button.
https://app.asana.com/0/599212887649773/1208605886979064/f
> Align all headers and remove extra scroll down button

- style.css
DWM - HP - Testimonials - Mobile - too much spacing above and bellow the carousel
[Link](https://app.asana.com/0/599212887649773/1208594946846724/f)
> made carosoul spacing smaller

- template-parts/template-services.php
Created Accordion feature for Service page (Mobile and Desktop).
> Accordion feature created in SP for mobile/desktop view

- single-demo.php
> Designdemos

- style.css
DWM - HP - Testimonials - Mobile - Center align the prev/next buttons horizontally 
[Link](https://app.asana.com/0/599212887649773/1208628746363569/f)
> centered buttons

- style.css
DWM - HP - Testimonials - Mobile - too much spacing above and bellow the carousel
[Link](https://app.asana.com/0/599212887649773/1208594946846724/f)
> added margin

- 404.php
- single-projects.php
- style.css
https://app.asana.com/0/599212887649773/1208653100292456/f
> Restyled 404 page

- template-parts/template-home.php
Increased gap between featured blog title and description in HP
Ticket Link: https://app.asana.com/0/599212887649773/1208594946846712/f
> Fixed gap between featured blog title and description in HP

- style.css
DWM - HP - Hero H1 reduces font size on a tablet
[Link](https://app.asana.com/0/599212887649773/1208653504778854/f)
> changed the font size

- template-parts/template-home.php
DWM - HP - Services section - change text on the button from Our Services to Learn more about our services
[Link](https://app.asana.com/0/599212887649773/1208653504778863/f)
> changed Text

- style.css
DWM - HP - Services section - change text on the button from Our Services to Learn more about our services
[Link](https://app.asana.com/0/599212887649773/1208653504778863/f)
> button overlap removed

- 404.php
- style.css
Removed Recent Posts, Most Used Categories, Archives and Tags, and also added the return to homepage button.
https://app.asana.com/0/1208404305074169/1208653100292456/f
> 404 Page - Remove extra content and add homepage button

- style.css
- template-parts/template-home.php
DWM - HP - Services section - Mobile - reduce the h2 font size from 60 to 30px and set the line height to auto
[Link](https://app.asana.com/0/599212887649773/1208628746363576/f)
> changed heading

- style.css
- template-parts/template-services.php
Replaced numbers with service specific icons in SP
Ticket number: https://app.asana.com/0/1208404278452601/1208653504778857/f
> Replaced numbers with icons in SP

- style.css
HP featured projects - featured images- Increase the radius on rounded corders and also add a green border around the image on hover
[Link](https://app.asana.com/0/599212887649773/1208653508853381/f)
> border on hover

- style.css
- template-parts/template-services.php
https://app.asana.com/0/599212887649773/1208653504778857/f
> Icons for services in sp

- style.css
- template-parts/template-services.php
Reverts DreamWay-Media/dwm-wp-theme#144
> Revert "Revert "Icons for services in sp""

- style.css
- template-parts/template-home.php
- template-parts/template-projects.php
DWM - Portfolio Listing
[Link](https://app.asana.com/0/599212887649773/1208680582585943/f)
> tags placement made lower

- style.css
DWM - HP - Hero H1 reduces font size on a tablet
[Link](https://app.asana.com/0/599212887649773/1208653504778854/f)
> changed styling

- single-projects.php
Prevented the blank gallery from appearing, it will only appear if there is a gallery.
https://app.asana.com/0/1208404305074169/1208692440942204/f
> Remove blank gallery from page if empty

- scss/pages/_common.scss
- scss/pages/_home.scss
- single.php
- template-parts/template-home.php
DWM - HP - Featured Blog section links
[Link](https://app.asana.com/0/599212887649773/1208876034652009/f)
> changed read more in homepage

- scss/base/_media-queries.scss
- scss/components/_footer.scss
DWM - footer menu wraps on desktop when more links are added to it[Link](https://app.asana.com/0/599212887649773/1208876034652022/f)
> changes to accomodate footer menu

- template-parts/template-home.php
DWM - Featured Projects - Reduce six projects to three projects.
[Link](https://app.asana.com/0/599212887649773/1208939349503745/f)
> changed  featured post number from 6 to 3

- assets/js/logosHorizontalScroll.js
- functions.php
- scss/pages/_home.scss
- template-parts/template-home.php
Add a new section on the homepage that shows our clients' logos. [Link](https://app.asana.com/0/599212887649773/1208412294319307/f)
> added logo scroll feature

- assets/js/logosHorizontalScroll.js
- scss/pages/_home.scss
- template-parts/template-home.php
[Link](https://app.asana.com/0/599212887649773/1208412294319307/f)
> made fixes to the logos scroll

- header.php
- template-parts/template-services.php
1. Connected Services drop-down items to the respective accordion items.
2. Services range  in the HP page are now connected to the accordion items and toggle accordingly.
Ticket link: https://app.asana.com/0/599212887649773/1208562315891804/f
> Accordion navmenu

- scss/pages/_home.scss
Add a new section on the homepage that shows our clients' logos. 
[Link](https://app.asana.com/0/599212887649773/1208412294319307/f)
> decreased speed

- header.php
- template-parts/template-services.php
Updated accordion-navmenu for smaller screen visibility issue
Ticket link: https://app.asana.com/0/599212887649773/1208562315891804/f
> Updated accordion-navmenu for smaller screen visibility issue

- footer.php
- scss/base/_media-queries.scss
- scss/components/_footer.scss
Eco-friendly/Carbon-free tags added to footer
https://app.asana.com/0/599212887649773/1208930496345915/f
> Eco-friendly/Carbon-free tags added to footer

- scss/pages/_blog.scss
- template-parts/template-blog.php
New style for blog pagination
https://app.asana.com/0/599212887649773/1208905606654723
> New style for blog pagination

- footer.php
- scss/components/_footer.scss
Updated placement and logo for eco friendly tag
https://app.asana.com/0/599212887649773/1208930496345915
> Updated placement and logo for eco friendly tag

- footer.php
Eco-friendly tag connected to blog
https://app.asana.com/0/599212887649773/1209517139172255
> Eco-friendly tag connected to blog

- footer.php
Carbon tag reset - only in footer
> Carbon tag reset
